#!/usr/bin/env bash
##-------------------------------
## Script    : Hilda
## Versão    : Desenvolvimento
## Autor     : Nicholas Affonso
## Ciado em  : 17 01 2023
## Licença   : GNU/GPL v3.0
##-------------------------------
## Descrição : 
##
## Kona é um programa que facilita
## o processo de configuração de um
## ambiente de desenvolvimento básico
##-------------------------------
## Uso: 
##
## Dê permissão de execução ao arquivo kona
## e inicie o programa com comando ./kona
##
## Leia o documento README para mais informações
##-------------------------------

#!/bin/bash

# Atualiza
apt update
apt upgrade

# Habilita o acesso ao sistema de arquivos
termux-setup-storage

# Cria estrutura de diretótios
mkdir ~/nic/dev

# Instalando programas
apt install -y $(cat pkgs)

# Configurando o git
git config --global user.name
git config --global user.email

# Gerando chaves de criptografia
rm -rf ~/.ssh
ssh-keygen -t ed25519 -C "nicholasaffonsop@gmail.com"
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_ed25519

# Termux-style (color theme)
git clone https://github.com/adi1090x/termux-style ~/.termux-style

cd ~/.termux-style
./install

cd ~
ln -s -f .tmux/.tmux.conf
cp .tmux/.tmux.conf.local .

# Oh-My-Bash
bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"

# Fsociety Hacking Tools Pack – PenTest Framework
pip install fsociety


